### ISSUE TITLE
ERROR after Starting when a WSDL document from Config is unavailable

### ISSUE THREAD

**Issue by predic8** [membrane/client#2]
The GUI shows:

Plug-in com.predic8.plugin.membrane_client was unable to load class

**Comment by predic8** [comment]
- Show unavailable WSDLs with Error Icon
- Tooltip: WSDL is unavailable. Please check location at: http://.....
- Rightclick: Reload => Try again

**Comment by am29d** [comment]
should be fixed with last commit
