### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by ppazos** [membrane/client#5]
this url doesnt work any more  http://www.membrane-soa.org/soap-client/

**Comment by predic8** [comment]
No. We do not develop the client any more.

Cheers,

Thomas

Am 07.08.16, 22:35 schrieb "Pablo Pazos" notifications@github.com:

this url doesnt work any more http://www.membrane-soa.org/soap-client/

**Comment by ppazos** [comment]
thanks, I would suggest to update the readme removing the link and adding a comment about this tool not being supported, thanks
